#Post-Install Tasks after spinning up new virtual machines on Oracle Linux and Ubuntu
#Author = oceanfabreeze
#Version = 1.0

- hosts: oraclelinux
  tasks:
    - name: Make sure everything is up to date ORACLE Nodes
        ansible.builtin.command: yum -y upgrade
        become: true
        register: command_output
        - debug:
              var: command_output.stdout_lines
        ansible.builtin.command: yum -y install epel-release
                become: true
                register: command_output
                - debug:
                      var: command_output.stdout_lines
        ansible.builtin.command: yum repolist
                become: true
                register: command_output
                - debug:
                      var: command_output.stdout_lines

- hosts: ubuntuserver
  tasks:
    - name: Make sure everything is up to date UBUNTU
      ansible.builtin.shell:
        cmd: sudo apt-get update
        cmd: sudo apt-get -y upgrade
        become: true

#####Start OS Agnostic Checks/Installs#####

- hosts: all
  vars:
    packages:
      - htop
      - git
      - samba

  tasks:
    - name: Check to make sure everything is installed
      package:
        name: "{{ packages }}"
        state: latest
    - name: Confirmed!
      debug:
        msg: Packages have been installed successfully.
