#Post-Install Tasks after spinning up new virtual machines on Oracle Linux and Ubuntu
#Author = oceanfabreeze
#Version = 1.0

- hosts: oraclelinux
  tasks:
    - name: Make sure everything is up to date ORACLE
      ansible.builtin.command: yum -y upgrade
      register: command_output
    - debug:
        var: command_output.stdout_lines

    - name: Check if EPEL is enabled ORACLE
      ansible.builtin.command: yum -y install epel-release
      register: command_output
    - debug:
        var: command_output.stdout_lines

    - name: Check and output RepoList ORACLE
      ansible.builtin.command: yum repolist
      register: command_output
    - debug:
        var: command_output.stdout_lines

- hosts: ubuntuserver
  tasks:
    - name: Make sure everything is up to date UBUNTU
      shell: sudo apt-get upgrade
      become: true
      register: command_output
    - debug:
        var: command_output.stdout_lines
        
#####Start OS Agnostic Checks/Installs#####

- hosts: all
  vars:
    packages:
      - htop
      - git
      - samba

  tasks:
    - name: Check to make sure everything is installed
      package:
        name: "{{ packages }}"
        state: latest
    - name: Confirmed!
      debug:
        msg: Packages have been installed successfully.
